# This is a basic workflow to help you get started with Actions

name: Linux-Flatpak CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
    # Setup Packages
    - name: Setup Packages
      run: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo && flatpak install org.kde.Sdk//5.15 org.kde.Platform//5.15 -y && dnf install libusb1-devel cmake git gcc-c++ libXext-devel libgudev qt6-qtbase-devel systemd-devel openal-soft-devel libevdev-devel libao-devel SOIL-devel libXrandr-devel pulseaudio-libs-devel bluez-libs-devel p7zip SDL2-devel SDL2_net -y
    # Run Flatpak Builder
    - name: Run Flatpak Builder
      uses: flatpak/flatpak-github-actions@v2
      with:
        # The relative path of the manifest file.
        manifest-path: Package/flatpak.yml
        # The bundle name, by default it's app.flatpak
        bundle: MupenMPN-linux.flatpak
    # Upload Artifact
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MupenMPN-Linux-flatpak
        path: /home/runner/work/Mupen-MPN-src/Mupen-MPN-src/.flatpak/OUT
